### ISSUE TITLE
ADD_ADDR: ports support

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#54]
As defined in RFC8684:

> The 2 octets that specify the TCP port number to use are optional, and their presence can be inferred from the length of the option. Although it is expected that the majority of use cases will use the same port pairs as those used for the initial subflow (e.g., port 80 remains port 80 on all subflows, as does the ephemeral port at the client), there may be cases (such as port-based load balancing) where the explicit specification of a different port is required. If no port is specified, MPTCP SHOULD attempt to connect to the specified address on the same port as the port that is already in use by the subflow on which the ADD_ADDR signal was sent; this is discussed in more detail in Section 3.9.

https://www.rfc-editor.org/rfc/rfc8684.html#name-address-advertisement

If needed, new tickets can be created to track: receiver/sender side only and packetdrill support.

- [x] Kernel: receive ADD_ADDR with port support + create new subflow on this different port if OK
- [x] Kernel: send ADD_ADDR with port support + accept new subflow on this different port if OK
- [x] Kernel: selftests
- [ ] iproute2 support: see #166 
- [ ] Packetdrill (if possible): see #169 

(Feature from the initial roadmap)

**Comment by matttbe** [comment]
I just checked two items of the checklist above:

- [x] Kernel: send ADD_ADDR with port support + accept new subflow on this different port if OK
- [x] Kernel: selftests

Thanks to new patches from Geliang now in the repo:

- 439600160048: mptcp: create the listening socket for new port
- 3122c6542e4f: mptcp: drop unused skb in subflow_token_join_request
- 9dfc9b337d4f: mptcp: add a new helper subflow_req_create_thmac
- 551edb8d92ab: mptcp: add port number check for MP_JOIN
- 3f96f48fbd19: mptcp: enable use_port when invoke addresses_equal
- 60e993388f4f: mptcp: deal with MPTCP_PM_ADDR_ATTR_PORT in PM netlink
- 7e876f36d164: selftests: mptcp: add port argument for pm_nl_ctl
- e7b4ca22e5fb: mptcp: add the mibs for ADD_ADDR with port
- 4eed52217818: selftests: mptcp: add testcases for ADD_ADDR with port
- Results: 2535f605affc..5f5277ef3bf4

One item left:

- [ ] Packetdrill (if possible)

(we should discuss if we can continue without but packetdrill tests to validate such features make a lot of sense! Once we have these tests, we might even not execute some selftests subtests that are quite slow compared to Packetdrill ones. If packetdrill is an issue, please share this here :) )

**Comment by matttbe** [comment]
The two remaining items are handled in different stories:
- [ ] iproute2 support: see #166
- [ ] Packetdrill (if possible): see #169

We can then close this one.
